#cloud-config
disable_root: true
timezone: Europe/Moscow
repo_update: true
repo_upgrade: true

apt:
  preserve_sources_list: true
  sources:
    mongodb-org-4.2.list:
      source: "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse"
      key: |
              -----BEGIN PGP PUBLIC KEY BLOCK-----
              Version: GnuPG v1.4.11 (GNU/Linux)
              
              mQINBFrXrqYBEACscLj2qgPpHBCQtgW1Yh29Ddgv6jssyWLAYmj0qngFLKoQMMbt
              SNBZylIKxfS+pUD9J5xfRZwfZOmtMIOFVWS9tcpeQXsiwC126tRyoFCIpoTmH7+R
              8/FfPrCYyXLP+ftEZfRV60wTwr5drR0S5pVIST3oaXXGkHkFC35U++udUG2Tl4Cs
              OPSCp1tsK6UOTjHFDH8PnasImJgD37QC8OOMIJS0jCtDZywJW6OCdpIRbuTWPK3P
              P48NLwGUJHixhVCmOgPPu9kDAfG3wLxiN85S2UbaaSXsdA4fF4SSwWNHTIYAg0yT
              xGepVyW4lkfcvng4jva24rQ9j1cm1b7bWeOkMH1aAcSyFzKCeNCNxbVOYVrcWNP4
              zrSUvsTKhwX8rPFMq9LkcKirDL9bRILvn/24VU6NdJfGbRjR6+Q7ooj7hYKLXtO5
              q0Q4nhjigpTWIoU6jdfbM9YqpKSELNnkDRAU+bRYSrNaFuizYgDZQvcVT6gbq26f
              JbgihoeJogEfim3kqRRJ3EUhE+EaVijl9iLDKkpurod26P2QSq9RKSuOCeauPjQv
              3BIiEMXco8O3v8W1y4TbnSQ3d28W9pN28IgAhmN2EU2sKqWPzNeG0V+L6mE5pA4o
              nD3z3JRpxAUFw08+9LnLRZ4D1u54OrHADsU8UpYZJCm1xw6T0e4dlxW6rQARAQAB
              tDdNb25nb0RCIDQuMiBSZWxlYXNlIFNpZ25pbmcgS2V5IDxwYWNrYWdpbmdAbW9u
              Z29kYi5jb20+iQI+BBMBAgAoBQJa166mAhsDBQkJZgGABgsJCAcDAgYVCAIJCgsE
              FgIDAQIeAQIXgAAKCRBLfFSaBY+LaxdXEACJMvkgr3Nt2xme9/6brGMbrEy6mQn7
              DZP98DXuS0tWvO5vkEO5IfRIvzG3zA0pATSBDVA0BvGnebQrGXZZ7Xfh0gz+zxlt
              TXv4eCyb6T4gRJuuQSFPTyDnZ3MbPESqj0UpIALmcLDJ01nqvbNPKxx5r08XQOtE
              i44Kcwc1Px5cPcYP9nmpDNLZjz3gkTm+zBygdE9beP02qXq7WcyghFmQZoLBW53e
              TqNPnMrrm5+6vgq+r/ttyiYTo7Zw8MrifN5okevzB0JhhSAW9g+4ZOp1QYbV8u8V
              pksJQDOIaBWIw8zosIQJTCVyd4hOyl8Ib2s2R0/grT51RgLYCNbUG6WTpKGgYBtr
              Mng10gozyDrnA3B+RiDx5uq+dNzuuMXWMit2nbcdanXdKNkaPmC6WVeU0rG5K1Wz
              jQMDvAInTszLcqH6zfEsjCoXj0z8UwcC4jahFDNMDBk3OhjMSL+fnvIhW84nKVHf
              AWL5jjSQdkrM/M8QRpRqls5apuIYHQwo6Oyd2Nk0n9T/GOMJ1jilxiPw9ihusf+k
              DfU0JI7T8fgxIv/wHNXUg7FOaaDJIfgGlCPUgtsNUDZZ9lFq+Zc5H8Wff3LNo7Se
              2xnzzoy2e+C3tsxAmVUTs+q0lyIzEK24lf71cp074KVV7rIYBELYtO2hAlJYjXJU
              bscTTjCKLf9leA==
              =UXPP
              -----END PGP PUBLIC KEY BLOCK-----


users:
    - default
    - name: ubuntu
      sudo: ALL=(ALL) NOPASSWD:ALL
      shell: /bin/bash
      ssh-authorized-keys:
        - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDJ6x+RcFWEHRowLl9teeMmjU6SzqdxPl2iEBt9a2PKf/teZjNoH18Lrc1FYNEBbiR8drWkVmVhBq7DzX5R3ShHPtdYYz0AnOgpv5U/K4g0LfdPkAruv+RfTmFE4MlcwkXp0R9BXYLmz9lnTd5ioXNSm1DX+X5WJLEm/eQ1i3FeRvzcLEFD/l/q8NeTtraTQgmSCZThQ8dF63LCJPUCbBb+owM3ARC8gW614dXeF+o3fU4RbCABzS1MlAnHhY/TMakIXBOjN9lzzMydVy7xtzWlOPGklqvV+k1DLE34G2V/19hHfcvKmeAuXNMRI9CUR7eLxW1Z7iaAn664vkMd4hYBubX636RRwOWqpGrQb8hefHwNst6vRkG5/lj+T4dzMp6O88trO8gI4ANM/PNBOam58WswltRASW+GuBFUKET+sJI1aOyKGTNRomcqsxDArFVF6kWjwjPxh8uiX/M3dm21sq8+gSQJEQl3rwGqdaAEKwwxZNiY/YH/u06InpQOhls= appuser"

packages:
  - git
  - ruby-full
  - ruby-bundler
  - build-essential
  - mongodb-org

runcmd:
  - [ sudo, systemctl, start, mongod ]
  - [ sudo, systemctl, enable, mongod ]
  - [ git, clone, -b, monolith, "https://github.com/express42/reddit.git" ]
  - [ cd, reddit ]
  - [ sudo, bundle, install ]
  - [ puma, -d]

final_message: "The system is finally up, after $UPTIME seconds"
