---
- name: Install MongoDB
  hosts: all
  become: true
  tasks:
    - name: Add key for Repo
      apt_key:
        id: EA312927
        keyserver: keyserver.ubuntu.com

    - name: Add APT repository
      apt_repository:
        repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
        state: present

    - name: Install MongoDB
      apt:
        name: mongodb-org
        state: present
        allow_unauthenticated: yes

    - name: Enable service MongoDB
      systemd:
        name: mongod
        enabled: yes
