---
- name: Install Ruby and Bundler
  hosts: all
  become: true
  tasks:
    - name: Install Ruby
      apt:
        name: ruby-full
        state: present
        update-cache: yes
    - name: Install ruby-bundler
      apt:
        name: ruby-bundler
        state: present
    - name: Install build-essential
      apt:
        name: build-essential
        state: present

  tags: app-install-tag
